// Changelog der Dashboard-Version 2 (Änderungen nach dem 28.09.2026)
window.DASHBOARD_CHANGELOG = {
  version: "2.0.0",
  date: "2026-10-04",
  de: {
    added: [
      "Versionspunkt in der Seitenleiste mit Changelog-Fenster",
      "Standard-Widgets auf der Übersicht beim ersten Start",
      "Wiederverwendbare Widget-Komponenten: eine Quelle, Klone auf Übersicht und Unterseiten",
      "Dasselbe Widget mehrfach einbinden, z. B. zwei Wetterorte oder zwei Pegel zum Vergleich",
      "Kachellayout im F-Muster von links nach rechts, Zeile für Zeile",
      "Kacheln bleiben im sichtbaren Bereich, auch nach manuellem Anordnen",
      "Warn-Banner oben auf allen Seiten mit Lauftext, konfigurierbar unter Organisation",
      "Seitenleistenpunkt „Gegen Langeweile“ mit Spielkacheln (Klondike-Solitaire und Tic Tac Toe)",
    ],
    changed: [
      "Schriften größer als Full HD (über 1920 px Breite, typisch >27\"): aus etwa 1,4–2 m lesbar; darunter, Tablet und Mobil die kompakte Größe",
      "Widgets im Anordnen-Modus frei in Breite und Höhe skalieren",
      "Kleine Kacheln rücken in den freien Raum neben hohen Widgets",
      "Eine gemeinsame Widget-Fläche pro Seite statt getrennter Reihen",
      "Zurücksetzen der Übersicht stellt die Standard-Widgets wieder her, statt sie zu löschen",
      "README enthält nur lokalen Start und den Live-Link, alles Weitere steht in der Dokumentation",
      "Theme-Wechsel (Hell/Dunkel) angepasst",
      "Farbschema, Diagramme und Kacheloptik",
      "Kacheln umschließen ihren Inhalt statt die Seite zu füllen",
      "Wetterseite: Regenradar unter aktuellem Wetter, Vorhersage an den Balken",
      "Übersicht und Unterseiten zeigen dieselbe Widget-Darstellung",
      "Die Seite Katastrophenschutz heißt Organisation",
    ],
    removed: ["Familien-Treffpunkt"],
    fixed: [
      "Skalierung bei hohen Bildschirmauflösungen",
      "7-Tage-Wetter wird korrekt dargestellt",
      "Feuerwehr-Einsätze werden wieder angezeigt",
      "Widgets lassen sich nur noch im Modus Anordnen entfernen",
      "Wetter-Leuchteffekt bleibt innerhalb der Kachel",
      "Regenradar überlappt die Vorhersage nicht mehr",
      "Pegelverlauf füllt die Kachel beim Skalieren",
      "Pegel-Buttons so breit wie ihr Text",
      "Kennzahlen (Wetter, Feuerwehr, Pegel) als einzelne Widgets mit eigener Überschrift",
      "Nach Zurücksetzen der Wetterseite lässt sich die Breite wieder anpassen",
    ],
  },
  en: {
    added: [
      "Version item in the sidebar with a changelog dialog",
      "Default widgets on the overview at first launch",
      "Reusable widget components: one source, clones on overview and subpages",
      "Add the same widget more than once, e.g. two weather places or two gauges for comparison",
      "F-pattern tile layout from left to right, row by row",
      "Tiles stay in view even after manual Arrange",
      "Warning banner at the top of every page with scrolling text, configured under Organisation",
      "Sidebar item “Against boredom” with game tiles (Klondike solitaire and tic-tac-toe)",
    ],
    changed: [
      "Larger type above Full HD (over 1920 px wide, typically >27\"): readable from about 1.4–2 m; compact type below that, including tablet and phone",
      "Widgets scale freely in width and height in Arrange mode",
      "Small tiles move into the free space beside tall widgets",
      "One shared widget area per page instead of separate rows",
      "Resetting the overview restores the default widgets instead of deleting them",
      "README covers local start and the live link only; everything else is in the documentation",
      "Theme switch (light/dark) adjusted",
      "Colour theme, charts and tile appearance",
      "Tiles hug their content instead of filling the page",
      "Weather page: rain radar under current weather, forecast hugging the bars",
      "Overview and subpages share the same widget look",
      "The Civil protection page is now called Organisation",
    ],
    removed: ["Family meeting point"],
    fixed: [
      "Scaling at high display resolutions",
      "7-day weather is shown correctly",
      "Fire brigade incidents are shown again",
      "Widgets can only be removed in Arrange mode",
      "Weather glow stays inside the tile",
      "Rain radar no longer overlaps the forecast",
      "Water level chart fills the tile when resized",
      "Gauge buttons as wide as their label",
      "Key figures (weather, fire brigade, water levels) as individual widgets with their own heading",
      "After resetting the weather page, width can be adjusted again",
    ],
  },
};
